### ISSUE TITLE
!uptime is broken with `unhandled KeyError`

### ISSUE THREAD

**Issue by jbpratt78** [anthonywritescode/twitch-chat-bot#19]
:smile_cat: for a later date. Not sure what has changed :thinking: 

https://dev.twitch.tv/docs/api/reference#get-streams

**Comment by Senpos** [comment]
[Twitch now requires oauth_token for every helix endpoint](https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916)

You may generate it as described here: https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-client-credentials-flow

Keep in mind, your generated `access_token` should match `client_id`

P. S. it is so annoying lol
