### ISSUE TITLE
Unknown command fuzzy finding.

### ISSUE THREAD

**Issue by Xithrius** [anthonywritescode/twitch-chat-bot#62]
When a command isn't found, the bot outputs a medium-sized wall of text that may be expanded in the future.

Having a fuzzy finder for listing out up to 3 (?) commands that are similar to the command the user is trying to run would reduce the reading a user would have to do.

Maybe in the future a page in GitHub (written in markdown) could be had with gifs showing an example of what each command does.

**Comment by Senpos** [comment]
Added in https://github.com/anthonywritescode/twitch-chat-bot/pull/74
